#if !canImport(ObjectiveC)
  import XCTest

  extension RxWebKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RxWebKitTests = [
      ("HasEventsBehavior_Optional_String____Has_Events_Behavior__Actually_got_the_event", HasEventsBehavior_Optional_String____Has_Events_Behavior__Actually_got_the_event),
      ("HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event", HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event),
      ("HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_2", HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_2),
      ("HasEventsBehavior_Double___Has_Events_Behavior__Actually_got_the_event", HasEventsBehavior_Double___Has_Events_Behavior__Actually_got_the_event),
      ("HasEventsBehavior_Double___Has_Events_Behavior__Actually_got_the_event_2", HasEventsBehavior_Double___Has_Events_Behavior__Actually_got_the_event_2),
      ("HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_3", HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_3),
      ("HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_4", HasEventsBehavior_Bool___Has_Events_Behavior__Actually_got_the_event_4),
      ("ForwardsEventsBehavior__b__sentMessage", ForwardsEventsBehavior__b__sentMessage),
      ("ForwardsEventsBehavior__b__methodInvoke", ForwardsEventsBehavior__b__methodInvoke),
      ("ForwardsEventsBehavior__b__sentMessage_2", ForwardsEventsBehavior__b__sentMessage_2),
      ("ForwardsEventsBehavior__b__methodInvoke_2", ForwardsEventsBehavior__b__methodInvoke_2),
      ("ForwardsEventsBehavior__b__sentMessage_3", ForwardsEventsBehavior__b__sentMessage_3),
      ("ForwardsEventsBehavior__b__methodInvoke_3", ForwardsEventsBehavior__b__methodInvoke_3),
      ("ForwardsEventsBehavior__b__sentMessage_4", ForwardsEventsBehavior__b__sentMessage_4),
      ("ForwardsEventsBehavior__b__methodInvoke_4", ForwardsEventsBehavior__b__methodInvoke_4),
      ("ForwardsEventsBehavior__b__sentMessage_5", ForwardsEventsBehavior__b__sentMessage_5),
      ("ForwardsEventsBehavior__b__methodInvoke_5", ForwardsEventsBehavior__b__methodInvoke_5),
      ("ForwardsEventsBehavior__b__sentMessage_6", ForwardsEventsBehavior__b__sentMessage_6),
      ("ForwardsEventsBehavior__b__methodInvoke_6", ForwardsEventsBehavior__b__methodInvoke_6),
      ("ForwardsEventsBehavior__b__sentMessage_7", ForwardsEventsBehavior__b__sentMessage_7),
      ("ForwardsEventsBehavior__b__methodInvoke_7", ForwardsEventsBehavior__b__methodInvoke_7),
      ("ForwardsEventsBehavior__b__sentMessage_8", ForwardsEventsBehavior__b__sentMessage_8),
      ("ForwardsEventsBehavior__b__methodInvoke_8", ForwardsEventsBehavior__b__methodInvoke_8),
      ("ForwardsEventsBehavior__b__sentMessage_9", ForwardsEventsBehavior__b__sentMessage_9),
      ("ForwardsEventsBehavior__b__methodInvoke_9", ForwardsEventsBehavior__b__methodInvoke_9)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(RxWebKitTests.__allTests__RxWebKitTests)
    ]
  }
#endif
