---
version: 2
jobs:
  "RxWebKit Tests":
    working_directory: ~/RxSwiftCommunity/RxWebKit
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '13.1.0'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: Bootstrap Carthage
          command: |
            brew update
            brew upgrade carthage
            carthage update --use-xcframeworks
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: Build macOS (Swift 5.0)
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.5.1 -workspace RxWebKit.xcworkspace -scheme RxWebKit -sdk macosx -destination "arch=x86_64" | xcpretty -c
      - run:
          name: Build iOS (Swift 5.0)
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.5.1 -workspace RxWebKit.xcworkspace -scheme RxWebKit -sdk iphonesimulator -destination "name=iPhone 12" | xcpretty -c
                    
      - run:
          name: Build tvOS (Swift 5.0)
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.5.1 -workspace RxWebKit.xcworkspace -scheme RxWebKit -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty -c
      - run:
          name: Run Tests (Swift 5.0)
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.5.1 -workspace RxWebKit.xcworkspace -scheme 'RxWebKitTests-iOS' -sdk iphonesimulator -destination "name=iPhone 12" | xcpretty -c --test
      - store_artifacts:
          path: /tmp/xcode-test-results
workflows:
  version: 2
  build:
    jobs:
      - "RxWebKit Tests":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
              