---
version: 2
jobs:
  "RxWebKit Tests":
    working_directory: ~/RxSwiftCommunity/RxWebKit
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: Bootstrap Carthage
          command: carthage update --no-use-binaries
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: Build (Swift 5.0)
          command: >
                   set -o pipefail && xcodebuild build SWIFT_VERSION=5.0
                   -workspace RxWebKit.xcworkspace
                   -scheme 'RxWebKit' -sdk iphonesimulator
                   -destination "name=iPhone Xʀ" | xcpretty -c
      - run:
          name: Run Tests (Swift 5.0)
          command: >
                   set -o pipefail && xcodebuild test SWIFT_VERSION=5.0
                   -workspace RxWebKit.xcworkspace
                   -scheme 'RxWebKitTests' -sdk iphonesimulator
                   -destination "name=iPhone Xʀ" | xcpretty -c --test
      - store_artifacts:
          path: /tmp/xcode-test-results
workflows:
  version: 2
  build:
    jobs:
      - "RxWebKitTests":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
